name: VPS cua binhdeptrai

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Nhập code remote'
        required: true
      pincode:
        description: 'Nhập mã pin tuỳ ý (6 số)'
        required: true
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Initializing Setup
      run: ./caidat.ps1
    - name: Khởi động VPS
      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
    - name: VPS đang chạy. Thời hạn còn lại:
      run: ./time.ps1
